root = "."
tmp_dir = "tmp"

[build]
  cmd = "mise run install"
  entrypoint = "/bin/true"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html", "env", "yml", "yaml", "toml"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = []
  exclude_file = []
  delay = 1000 # ms
  stop_on_error = true
  log = "air_errors.log"
  kill_delay = "2s"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
