root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ~/.local/bin/esb ./cmd/esb"
  bin = "esb"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "tpl", "tmpl"]
  kill_delay = "2s"

[log]
  time = false

[misc]
  clean_on_exit = true
