root = "."
tmp_dir = "tmp"

[build]
  cmd = "make install"
  bin = "/bin/true"
  delay = 500
  exclude_dir = ["tmp", "vendor"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "tpl", "tmpl"]
  kill_delay = "2s"

[log]
  time = false

[misc]
  clean_on_exit = true
